---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.addressSecret }}
  namespace: {{ .Values.esNamespace }}
  labels:
    template-hash: {{ .Values.extTempHash }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{ .Values.gcpsmSecretStore }}
    kind: SecretStore
  target:
    name: {{ .Values.addressSecret }}
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "{{ .Values.certNamespace }}"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "{{ .Values.certNamespace }}"

  data:
    - secretKey: {{ .Values.ipSecretKey }}
      remoteRef:
        key: {{ .Values.addressSecret }}

