---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ regexReplaceAll "\\W+" .Values.jenkinsUsername "-" }}
  namespace: {{ .Values.esNamespace }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{ .Values.gcpsmSecretStore }}
    kind: SecretStore
  target:
    name: {{ .Values.jenkinsUsername }}
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "{{ .Values.argocdNamespace }}"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "{{ .Values.argocdNamespace }}"

  data:
    - secretKey: {{ .Values.jenkinsUsernameKey }}
      remoteRef:
        key: {{ .Values.jenkinsUsername }}

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ regexReplaceAll "\\W+" .Values.jenkinsPassword "-" }}
  namespace: {{ .Values.esNamespace }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{ .Values.gcpsmSecretStore }}
    kind: SecretStore
  target:
    name: {{ .Values.jenkinsPassword }}
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "{{ .Values.argocdNamespace }}"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "{{ .Values.argocdNamespace }}"

  data:
    - secretKey: {{ .Values.jenkinsPasswordKey }}
      remoteRef:
        key: {{ .Values.jenkinsPassword }}

