{{- $namespaces := printf "%s, %s, %s" .Values.ciNamespace .Values.loggingNamespace .Values.argocdNamespace -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certName }}
  namespace: {{ .Values.certNamespace }}
  labels:
    template-hash: {{ .Values.tempHash }}
spec:
  secretName: {{ .Values.certSecretName }}
  issuerRef:
    name: {{ .Values.certIssuerRefName }}
    kind: ClusterIssuer
  commonName: "{{ .Values.certCommonName }}"
  dnsNames:
  - "{{ .Values.certDnsName }}"
  - "{{ .Values.certDnsCi }}"
  - "{{ .Values.certDnsMonitoring }}"
  - "{{ .Values.certDnsArgocd }}"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "{{ $namespaces }}"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "{{ $namespaces }}"
