apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wefninev-tk
  namespace: cert-manager
spec:
  secretName: wefninev-tk-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.wefninev.tk"
  dnsNames:
  - "wefninev.tk"
  - "*.wefninev.tk"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "jenkins, logging"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "jenkins, logging"
