apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certIssuerRefName }}
spec:
  acme:
    server: {{ .Values.acmeServer }}
    email: {{ .Values.acmeEmail }}
    privateKeySecretRef:
      name: {{ .Values.acmeAccountPrivateKey }}
    solvers:
    - dns01:
        cloudDNS:
          project: {{ .Values.projectID }}
          serviceAccountSecretRef:
            name: {{ .Values.gcpSecretSA }}
            key: {{ .Values.gcpSecretSACredentials }}
