apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certIssuerRefName }}
  temphash: {{ .Values.tempHash }}
spec:
  acme:
    server: {{ .Values.acmeServer }}
    email: {{ .Values.acmeEmail }}
    privateKeySecretRef:
      name: {{ .Values.acmeAccountPrivateKey }}
    solvers:
    - http01:
        ingress:
          class: nginx
