apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gcpSecretSA }}
  namespace: {{ .Values.certNamespace }}
type: Opaque
stringData:
  {{ .Values.gcpSecretSACredentials }}: |-
    {{ .Values.dnsServiceAccount }}
