apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gcpSecretSA }}
  namespace: {{ .Values.certNamespace }}
type: Opaque
data:
  {{ .Values.gcpSecretSACredentials }}: {{ .Values.dnsServiceAccount }}
